Included job to clone repositories as part of Gitea deployment

diff --git a/demo-environment/resources/10_gitea/setup-job.yaml b/demo-environment/resources/10_gitea/setup-job.yaml
--- a/demo-environment/resources/10_gitea/setup-job.yaml
+++ b/demo-environment/resources/10_gitea/setup-job.yaml
@@ -33,32 +33,51 @@ spec:
             -d '{"username":"gitea","password":"openshift","retype":"openshift","email":"gitea@gitea.com","send_notify":false}' \
             -H "Content-Type: application/json" \
             http://$GITEA_HOSTNAME/user/sign_up
+          
+          echo "-- Creating demo repository --"
+          git clone https://github.com/clbartolome/ocp-dev-101       
+          echo "------------------------------"   
 
-          echo "-- Creating application source repository"
+          echo "-- Creating lol-champions-app repository --"
           RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
             -u gitea:openshift \
-            -d '{"auto_init": true,"default_branch": "master","gitignores": "VisualStudioCode","name": "application-source","private": false,"trust_model": "default"}' \
+            -d '{"auto_init": true,"default_branch": "master","gitignores": "VisualStudioCode","name": "lol-champions-app","private": false,"trust_model": "default"}' \
             -H "Content-Type: application/json" \
             http://$GITEA_HOSTNAME/api/v1/user/repos)
 
           if [ "$RESPONSE" != "201" ]; then
-              echo "Error creating application source repository, error code: $RESPONSE"
+              echo "Error creating repository, error code: $RESPONSE"
               exit 1
           fi
 
-          git clone http://gitea:openshift@$GITEA_HOSTNAME/gitea/application-source
-          cd application-source
+          git clone http://gitea:openshift@$GITEA_HOSTNAME/gitea/lol-champions-app
+          cp -R ocp-dev-101/lol-champions-app/ lol-champions-app
+          cd lol-champions-app
           git config user.email "gitea@gitea.com"
           git config user.name "gitea"
-          mkdir .s2i
-          cat <<EOF >>.s2i/environment
-          MAVEN_S2I_ARTIFACT_DIRS=target/quarkus-app
-          S2I_SOURCE_DEPLOYMENTS_FILTER=app lib quarkus quarkus-run.jar
-          JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0
-          AB_JOLOKIA_OFF=true
-          JAVA_APP_JAR=/deployments/quarkus-run.jar
-          EOF
-          git add . && git commit -m "Added s2i configuration" && git push
+          git add . && git commit -m "Cloned Repository" && git push
+          cd ..
+          echo "------------------------------"   
+
+          echo "-- Creating lol-champions-deploy repository --"
+          RESPONSE=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST \
+            -u gitea:openshift \
+            -d '{"auto_init": true,"default_branch": "master","gitignores": "VisualStudioCode","name": "lol-champions-deploy","private": false,"trust_model": "default"}' \
+            -H "Content-Type: application/json" \
+            http://$GITEA_HOSTNAME/api/v1/user/repos)
+
+          if [ "$RESPONSE" != "201" ]; then
+              echo "Error creating repository, error code: $RESPONSE"
+              exit 1
+          fi
+
+          git clone http://gitea:openshift@$GITEA_HOSTNAME/gitea/lol-champions-deploy
+          cp -R ocp-dev-101/lol-champions-deploy/ lol-champions-deploy
+          cd lol-champions-deploy
+          git config user.email "gitea@gitea.com"
+          git config user.name "gitea"
+          git add . && git commit -m "Cloned Repository" && git push
+          cd ..
           echo "------------------------------"
         imagePullPolicy: Always
       restartPolicy: Never
